### ISSUE TITLE
Failed to list stations

### ISSUE THREAD

**Issue by iddqdidkfa** [mopidy/mopidy-gmusic#146]
```
ERROR    Call to Google Music failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 31, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 121, in get_all_stations
    return self.api.get_all_stations()
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 760, in get_all_stations
    updated_after=updated_after)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1069, in _get_all_items
    return [s for chunk in generator for s in chunk]
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1082, in _get_all_items_incremental
    **kwargs)
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 227, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: ListStations: 500 Server Error: Internal Server Error
(requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v1.11/radio/station', u'headers': {u'Content-Type': u'application/json', u'Authorization': u'<omitted>'}, u'data': '{"max-results": "20000"}', u'method': u'POST', u'params': {u'alt': u'json', u'updated-min': 0, u'include-tracks': u'true'}})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "internalError",\n    "message": "Internal Error"\n   }\n  ],\n  "code": 500,\n  "message": "Internal Error"\n }\n}\n')
```

**Comment by iddqdidkfa** [comment]
After upgrading gmusicapi package I got another error:
```
AttributeError: 'Mobileclient' object has no attribute 'search_all_access'
```

**Comment by belak** [comment]
What version of mopidy-gmusic do you have? Can I get the output of mopidy deps?

**Comment by iddqdidkfa** [comment]
@belak Yeah you are right, my version is 1.0, thats the main reason of all problems. Just because 2.0 not released yet `pip` installs 1.0 and nothing works fine. Sorry for the inattention.

**Comment by belak** [comment]
`mopidy-gmusic` 2.0 is on my short list of things to do, but there's a pre-release version out now if you want to try that.

**Comment by iddqdidkfa** [comment]
@belak yeah thx. For those who may face same problem before release:
```
pip install git+https://github.com/mopidy/mopidy-gmusic.git
```
