### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy-gmusic#162]
I started to having an error, when launching mopidy:

```
2017-01-02 20:30:38,073 INFO [1659:MainThread] mopidy.commands: Starting Mopidy backends: GMusicBackend, StreamBackend, M3UBackend, FileBackend, LocalBackend
2017-01-02 20:30:38,106 INFO [1659:MainThread] gmusicapi.Mobileclient1: !-- begin debug log --!
2017-01-02 20:30:38,122 INFO [1659:MainThread] gmusicapi.Mobileclient1: version: 10.1.0
2017-01-02 20:30:38,125 INFO [1659:MainThread] gmusicapi.Mobileclient1: logging to: /var/lib/mopidy/.cache/gmusicapi/log/gmusicapi.log
2017-01-02 20:30:38,132 INFO [1659:MainThread] gmusicapi.Mobileclient1: initialized
2017-01-02 20:30:38,143 INFO [1659:MainThread] gmusicapi.Mobileclient1: logged out
2017-01-02 20:30:38,219 INFO [1659:Audio-2] mopidy.audio.actor: Audio output set to "autoaudiosink"
2017-01-02 20:30:42,204 WARNING [1659:GMusicBackend-3] requests.packages.urllib3.contrib.pyopenssl: A problem was encountered with the certificate that prevented urllib3 from finding the SubjectAlternativeName field. This can affect certificate validation. The error was Codepoint U+002A at position 1 of u'*' not allowed
2017-01-02 20:30:43,624 WARNING [1659:GMusicBackend-3] py.warnings: /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for android.clients.google.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

2017-01-02 20:30:43,657 ERROR [1659:GMusicBackend-3] requests.packages.urllib3.connection: Certificate did not match expected hostname: android.clients.google.com. Certificate: {'subjectAltName': [], 'subject': ((('commonName', u'*.google.com'),),)}
2017-01-02 20:30:44,840 ERROR [1659:GMusicBackend-3] pykka: Unhandled exception in GMusicBackend (urn:uuid:45700cd8-d39d-49f6-82a2-24a92fe058e0):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/backend.py", line 52, in on_start
    self.config['gmusic']['deviceid'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 61, in login
    authenticated = self.api.login(username, password, device_id)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 122, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 191, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 70, in perform_master_login
    return _perform_auth_request(data, proxy)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 26, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: hostname 'android.clients.google.com' doesn't match u'*.google.com'
2017-01-02 20:31:11,821 INFO [1659:MainThread] mopidy.local.library: Loaded 18057 local tracks using json
2017-01-02 20:31:11,831 ERROR [1659:MainThread] mopidy.commands: Actor died: GMusicBackend (urn:uuid:45700cd8-d39d-49f6-82a2-24a92fe058e0) not found
2
```

```
openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

```
pip show mopidy-gmusic
Name: Mopidy-GMusic
Version: 2.0.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: setuptools, cachetools, Pykka, requests, Mopidy, gmusicapi
```

```
 uname -a
Linux shuttle 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Do you have any clue how can I debug the issue?

**Comment by belak** [comment]
Are you still seeing this issue?

**Comment by morgoth** [comment]
I recently reinstalled system + mopidy and all looks fine
