### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by DelusionalLogic** [mopidy/mopidy-gmusic#171]
When refreshing the library I get the follow stacktrace on the commandline:

    ERROR    GMusicBackend backend caused an exception.
    Traceback (most recent call last):
      File "/home/delusional/.local/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
        yield
      File "/home/delusional/.local/lib/python2.7/site-packages/mopidy/core/library.py", line 269, in refresh
        future.get()
      File "/home/delusional/.local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
        compat.reraise(*self._data['exc_info'])
      File "/home/delusional/.local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
        exec('raise tp, value, tb')
      File "/home/delusional/.local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
        response = self._handle_receive(message)
      File "/home/delusional/.local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
        return callee(*message['args'], **message['kwargs'])
      File "/home/delusional/.local/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 317, in refresh
        mopidy_track = self._to_mopidy_track(track)
      File "/home/delusional/.local/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 500, in _to_mopidy_track
        name=song['title'],
    KeyError: u'title'

**Comment by belak** [comment]
There have been a number of tweaks in the last year or two which may have fixed this. Can you try a newer version and let me know if this doesn't fix the issue? Thanks!
