### ISSUE TITLE
Unable to seach all access tracks that aren't in library

### ISSUE THREAD

**Issue by ashgillman** [mopidy/mopidy-gmusic#173]
Hi,
I have an all access subscription, and I am using ncmpcpp.

I am not sure how to get access to music that I haven't added to my library. For music I have added to my library, I can browse through and play everything by that artist, not just the music I have explicitly added.

The front page README says:
> You can even add songs from your All Access subscription to your library.

So I am assuming this should be possible

My gmusic config is:

```
[gmusic]
enabled = true
username = gillmanash
password = ********
bitrate = 160
deviceid = 
all_access = true
refresh_library = 1440
refresh_playlists = 60
radio_stations_in_browse = true
radio_stations_as_playlists = true
radio_stations_count = 
radio_tracks_count = 25
```

**Comment by herrwusel** [comment]
I'm experiencing the same problem. Are you able to play songs from your 'liked'-playlist?

**Comment by ashgillman** [comment]
No, there are songs I have 'thumbs-up'ed that are not available in ncmpcpp via Browse->Google Music. I have to use the web interface, and select 'add to library', at which point they are browsable in mopidy.

**Comment by ashgillman** [comment]
I'm not sure if this is the intended design, or a bug. If given a pointer to where the issue, if it exists, may be, I am happy to attempt a solution myself.

**Comment by rosshadden** [comment]
I can no longer search either.  I had been using this for months, so it seems to have broken when something updated on my computers.

The errors I get when searching are:

```
Jul 23 21:29:58 tardis mopidy[6305]: 2017-07-23 21:29:58,010 - gmusicapi.Mobileclient1 (shared:281) [ERROR]: the response format for GetArtist was not recognized.
Jul 23 21:29:58 tardis mopidy[6305]: Value u'' for field '<obj>.name' cannot be blank'
Jul 23 21:29:58 tardis mopidy[6305]: First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following reques
Jul 23 21:29:58 tardis mopidy[6305]: {u'url': u'https://mclients.googleapis.com/sj/v2.5/fetchartist', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'num-related-artists': 0, u'nid': u'Adqzpvfe6gthjwcwycjziej3y7q', u'dv': 0, u'
Jul 23 21:29:58 tardis mopidy[6305]: u'{"kind":"sj#artist","name":"","artistId":"Adqzpvfe6gthjwcwycjziej3y7q"}'
Jul 23 21:29:58 tardis mopidy[6305]: A traceback follows:
Jul 23 21:29:58 tardis mopidy[6305]: Traceback (most recent call last):
Jul 23 21:29:58 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 249, in perform
Jul 23 21:29:58 tardis mopidy[6305]:     cls.validate(response, parsed_response)
Jul 23 21:29:58 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 627, in validate
Jul 23 21:29:58 tardis mopidy[6305]:     raise_from(ValidationException(str(e)), e)
Jul 23 21:29:58 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/six.py", line 718, in raise_from
Jul 23 21:29:58 tardis mopidy[6305]:     raise value
Jul 23 21:29:58 tardis mopidy[6305]: ValidationException: Value u'' for field '<obj>.name' cannot be blank'
Jul 23 21:29:58 tardis mopidy[6305]: ERROR    the response format for GetArtist was not recognized.
Jul 23 21:29:58 tardis mopidy[6305]: Value u'' for field '<obj>.name' cannot be blank'
Jul 23 21:29:58 tardis mopidy[6305]: First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following reques
Jul 23 21:29:58 tardis mopidy[6305]: {u'url': u'https://mclients.googleapis.com/sj/v2.5/fetchartist', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'num-related-artists': 0, u'nid': u'Adqzpvfe6gthjwcwycjziej3y7q', u'dv': 0, u'
Jul 23 21:29:58 tardis mopidy[6305]: u'{"kind":"sj#artist","name":"","artistId":"Adqzpvfe6gthjwcwycjziej3y7q"}'
Jul 23 21:29:58 tardis mopidy[6305]: A traceback follows:
Jul 23 21:29:58 tardis mopidy[6305]: Traceback (most recent call last):
Jul 23 21:29:58 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 249, in perform
Jul 23 21:29:58 tardis mopidy[6305]:     cls.validate(response, parsed_response)
Jul 23 21:29:58 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 627, in validate
Jul 23 21:29:58 tardis mopidy[6305]:     raise_from(ValidationException(str(e)), e)
Jul 23 21:29:58 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/six.py", line 718, in raise_from
Jul 23 21:29:58 tardis mopidy[6305]:     raise value
Jul 23 21:29:58 tardis mopidy[6305]: ValidationException: Value u'' for field '<obj>.name' cannot be blank'
Jul 23 21:29:59 tardis mopidy[6305]: ERROR    Call to Google Music failed
Jul 23 21:29:59 tardis mopidy[6305]: Traceback (most recent call last):
Jul 23 21:29:59 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
Jul 23 21:29:59 tardis mopidy[6305]:     return func(self, *args, **kwargs)
Jul 23 21:29:59 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 129, in get_artist_info
Jul 23 21:29:59 tardis mopidy[6305]:     max_rel_artist=max_rel_artist)
Jul 23 21:29:59 tardis mopidy[6305]:   File "<decorator-gen-136>", line 2, in get_artist_info
Jul 23 21:29:59 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
Jul 23 21:29:59 tardis mopidy[6305]:     return function(*args, **kw)
Jul 23 21:29:59 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1894, in get_artist_info
Jul 23 21:29:59 tardis mopidy[6305]:     artist_id, include_albums, max_top_tracks, max_rel_artist)
Jul 23 21:29:59 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 84, in _make_call
Jul 23 21:29:59 tardis mopidy[6305]:     return protocol.perform(self.session, self.validate, *args, **kwargs)
Jul 23 21:29:59 tardis mopidy[6305]:   File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 226, in perform
Jul 23 21:29:59 tardis mopidy[6305]:     raise CallFailure(err_msg, call_name)
Jul 23 21:29:59 tardis mopidy[6305]: CallFailure: GetArtist: 400 Client Error: Bad Request for url: https://mclients.googleapis.com/sj/v2.5/fetchartist?num-related-artists=0&nid=Aicozshoiwhx4ipqazbqhtp5lqu&dv=0&num-top-tracks=0&hl=en_US&ti
Jul 23 21:29:59 tardis mopidy[6305]: (requests kwargs: {u'url': u'https://mclients.googleapis.com/sj/v2.5/fetchartist', u'headers': {u'Authorization': u'<omitted>'}, u'params': {u'num-related-artists': 0, u'nid': u'Aicozshoiwhx4ipqazbqhtp5
Jul 23 21:29:59 tardis mopidy[6305]: (response was: u'{"error":{"errors":[{"domain":"global","reason":"badRequest","message":"Bad Request"}],"code":400,"message":"Bad Request"}}')
```

These errors seem to repeat indefinitely, as if retrying every so often.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
