### ISSUE TITLE
'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by GruberMischa** [mopidy/mopidy-gmusic#190]
So I'm just trying to setup mopidy and gmusic on my raspberry pi 3, and gmusic failes on startup with the following error:

`2018-04-03 09:31:30,344 ERROR [1477:MainThread] mopidy.__main__: Extension gmusic failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/__init__.py", line 45, in setup
    from .backend import GMusicBackend
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/backend.py", line 17, in <module>
    from .session import GMusicSession
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 6, in <module>
    import gmusicapi
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/__init__.py", line 4, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 18, in <module>
    from gmusicapi.protocol import webclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/webclient.py", line 19, in <module>
    from gmusicapi.protocol.shared import Call, authtypes
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 18, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
`

I also read, that there could be a problem with OpenSSL 1.0.1, but on my Pi version 1.1.0 is running

**Comment by kingosticks** [comment]
The first result on google seems like it would do the trick for you: https://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by GruberMischa** [comment]
Oh thanks, looks like I searched for the wrong issue. Now it works perfect!
