### ISSUE TITLE
ERROR Actor died: GMusicBackend

### ISSUE THREAD

**Issue by djl236** [mopidy/mopidy-gmusic#207]
Gmusic no longer working. Updated to latest version and still doesn't work.

I get this error:

Nov 03 11:51:41 mopidy mopidy[1670]: ERROR Actor died: GMusicBackend (urn:uuid:7b26d467-e1a0-4fd7-a297-2196b93a7434) not found  Now that UUID is not of my current phone but my old one. Perhaps I need to update that but I don’t see where. The config only has device id.

The UUID is that of my old iPhone and not my current Android phone. Is there a way to change or update the UUID? My device ID that I'm using is that of my current phone, and when I started Mopidy after entering the Device ID and app password, I received email notification of the login.

**Comment by jodal** [comment]
The error means that someone tried to message the GMusic backend actor, but it had already died. To find the reason for that, there should be a stack trace further up in the log. This message alone doesn't tell us enough to figure out the root cause.

The UUID in the message is the ID the actor had before it died. It has nothing to do with your phones or the `gmusic/device_id` config value.

**Comment by djl236** [comment]
ERROR    2018-11-12 10:49:12,532 [14460:GMusicBackend-3] pykka
  Unhandled exception in GMusicBackend (urn:uuid:ae5fb144-3237-4184-84c5-c0a5d5823988):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/backend.py", line 52, in on_start
    self.config['gmusic']['deviceid'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 61, in login
    authenticated = self.api.login(username, password, device_id)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 151, in login
    self.android_id = self._validate_device_id(device_id, is_mac=is_mac)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 66, in _validate_device_id
    raise InvalidDeviceId('Invalid device_id %s.' % device_id, device_ids)
InvalidDeviceId: Invalid device_id iosD9955459-B62B-40ED-B82F-DAB164FE98FF.Your valid device IDs are:
* f********************************edited out
* 3*******************************edited out
* 9*******************************edited out
* 3*******************************edited out
ERROR    2018-11-12 10:49:12,535 [14460:MainThread] mopidy.commands
  Actor died: GMusicBackend (urn:uuid:ae5fb144-3237-4184-84c5-c0a5d5823988) stopped before handling the message

I have my current device's deviceiD in the config. Do you know how I can get rid of that old iOS one?

**Comment by kingosticks** [comment]
Remove it from your mopidy config. `mopidy config` (or `sudo mopidyctl config` for the system service) shows the config settings that will be used. Perhaps you have not removed your old device ID from the correct mopidy config file.

**Comment by djl236** [comment]
ok so that was helpful and I'm part moron.

I'm running mopidy as a service BUT i still had the old ID in the non-service config (dummy!). Removed it and now it's working. Thanks guys.
