### ISSUE TITLE
ImportError: No module named cachetools

### ISSUE THREAD

**Issue by bubuntux** [mopidy/mopidy-gmusic#209]
from a fresh install i'm getting this error:

```
ERROR    Extension gmusic failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/home/jgutierrez/.local/lib/python2.7/site-packages/mopidy_gmusic/__init__.py", line 47, in setup
    from .backend import GMusicBackend
  File "/home/jgutierrez/.local/lib/python2.7/site-packages/mopidy_gmusic/backend.py", line 12, in <module>
    from .library import GMusicLibraryProvider
  File "/home/jgutierrez/.local/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 5, in <module>
    from cachetools import LRUCache
ImportError: No module named cachetools
```

pip2 list > 

pip2 list
```
Package                         Version
------------------------------- -------
apache-beam                     0.6.0  
appdirs                         1.4.3  
arandr                          0.1.9  
avro                            1.8.2  
backports-abc                   0.5    
Beaker                          1.10.0 
beautifulsoup4                  4.6.3  
bzr                             2.7.0  
CacheControl                    0.12.5 
cachetools                      2.0.1  
chardet                         3.0.4  
colorama                        0.4.1  
crcmod                          1.7    
decorator                       4.3.0  
dill                            0.2.6  
distlib                         0.2.8  
distro                          1.3.0  
funcsigs                        1.0.2  
future                          0.17.1 
futures                         3.2.0  
gmusicapi                       11.1.1 
google-apitools                 0.5.15 
google-auth                     1.1.1  
google-auth-httplib2            0.0.2  
google-cloud-bigquery           0.22.1 
googleapis-common-protos        1.5.2  
googledatastore                 7.0.0  
gpsoauth                        0.4.1  
html5lib                        1.0.1  
httplib2                        0.9.2  
idna                            2.8    
imageio                         2.2.0  
ipaddress                       1.0.22 
lockfile                        0.12.2 
louis                           3.8.0  
lxml                            4.2.5  
Mako                            1.0.7  
MarkupSafe                      1.1.0  
MechanicalSoup                  0.11.0 
mingc                           0.4.8  
mock                            2.0.0  
Mopidy                          2.2.1  
Mopidy-GMusic                   3.0.0  
msgpack                         0.5.6  
mutagen                         1.41.1 
oauth2client                    3.0.0  
olefile                         0.44   
packaging                       18.0   
pbr                             5.1.1  
pep517                          0.3    
pip                             18.1   
proboscis                       1.2.6.0
progress                        1.4    
proto-google-cloud-datastore-v1 0.90.0 
protobuf                        3.6.1  
pyasn1                          0.3.6  
pyasn1-modules                  0.1.4  
pycairo                         1.18.0 
pycryptodomex                   3.7.2  
PyGObject                       3.30.4 
Pykka                           1.2.1  
pyparsing                       2.3.0  
python-dateutil                 2.7.5  
pytoml                          0.1.20 
PyYAML                          3.12   
requests                        2.20.1 
retrying                        1.3.3  
rrdtool                         0.1.10 
rsa                             3.4.2  
setuptools                      40.6.2 
singledispatch                  3.4.0.3
six                             1.11.0 
team                            1.0    
tornado                         5.1.1  
urllib3                         1.24.1 
validictory                     1.1.2  
webencodings                    0.5.1  
wheel                           0.30.0
```
cachetools (2.0.1) is installed

**Comment by bubuntux** [comment]
Seems like updating all my pip installed packages solved the issue
