### ISSUE TITLE
Unable to play radio stations

### ISSUE THREAD

**Issue by arjvik** [mopidy/mopidy-gmusic#217]
Hi,

I've been using mopidy-gmusic for a while, and it works great to play all of my uploaded MP3s. However, it is unable to play any radio stations. I do not have All Access.

My config:
```
[gmusic]
enabled = true
username = ***
password = ***
bitrate = 160
deviceid = mac
all_access = true
refresh_library = 1440
refresh_playlists = 60
radio_stations_in_browse = true
radio_stations_as_playlists = false
radio_stations_count = 
radio_tracks_count = 25
top_tracks_count = 20
```

When I try to open a station in `ncmpcpp`, I get this error:

```
WARNING  Google Play Music All Access is required for get_station_tracks()
```

If I enable all_access in my config (even though I do not have it), I can view the tracks in the station (how?), and can add them to my playlist. However, when I try to play them I get this error:

```
ERROR    GMusicBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 423, in _change
    if not backend.playback.change_track(pending_tl_track.track).get():
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/backend.py", line 245, in change_track
    uri = self.translate_uri(track.uri)
  File "/home/arjvik/.local/lib/python2.7/site-packages/mopidy_gmusic/playback.py", line 24, in translate_uri
    track_id, quality=quality)
  File "/home/arjvik/.local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 32, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/arjvik/.local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 90, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "</home/arjvik/.local/lib/python2.7/site-packages/decorator.pyc:decorator-gen-104>", line 2, in get_stream_url
  File "/home/arjvik/.local/lib/python2.7/site-packages/gmusicapi/utils/utils.py", line 293, in wrapper
    return function(*args, **kw)
  File "/home/arjvik/.local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 452, in get_stream_url
    raise NotSubscribed("Store tracks require a subscription to stream.")
NotSubscribed: Store tracks require a subscription to stream. (https://goo.gl/v1wVHT)
WARNING  Track is not playable: gmusic:track:T6rfuvee3pdgrgddi6ole5e5xbu
```

Is it just not possible to play radio stations without All Access?

Thanks in advance!

**Comment by NonaSuomy** [comment]
Hello I really wanted this feature as well!

I was able to get help from my friend @foreverguest to implement this feature into gmusicapi with a lot of dedicated project management following it through. 

Just to get mopidy-gmusic and gmusicproxy to support it. 

We finally got stuck at this level as nobody I knew worked with this code base. 

You can review the flow here (The Google Radio Stations used to be Songza before Google bought them) 

[Mopidy-gmusic Issue 68](https://github.com/mopidy/mopidy-gmusic/issues/68) 

[GMusicProxy Issue 92](https://github.com/gmusicproxy/gmusicproxy/issues/92)

This feature has been in release since 11.0 of the gmusicapi. I'm not sure if release 3.0 of mopidy-gmusic was in support of version 11 of gmusicapi. 

Though as for version 4.0 it should be able to support it as it claims support for version 12 of gmusicapi. 

It would just require someone to add the feature from gmusicapi. 

If anyone knows a python-dev to add this support I'm sure a lot of people would like it! Seems like the only thing missing from this plugin. Thank you if anyone can figure it out!

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
