### ISSUE TITLE
EOF error initial_code = input("code: ")

### ISSUE THREAD

**Issue by FuzzyMistborn** [mopidy/mopidy-gmusic#236]
Trying to get this set up.  I run `mopidy gmusic login` and I see the link to get the initial auth code but right after that is the below error.  Am I doing something wrong?

Running mopidy 3.0.1 with GMusic 4.0 installed from pypi.

```
code: ERROR    2020-03-17 16:00:58,375 [39:MainThread] mopidy.__main__
  EOF when reading a line
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 143, in main
    return args.command.run(args, proxied_config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_gmusic/commands.py", line 23, in run
    initial_code = input("code: ")
EOFError: EOF when reading a line
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==3.0.1', 'console_scripts', 'mopidy')()
  File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 143, in main
    return args.command.run(args, proxied_config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_gmusic/commands.py", line 23, in run
    initial_code = input("code: ")
EOFError: EOF when reading a line

```

**Comment by FuzzyMistborn** [comment]
I was able to get this to work in another instance on a pi.  Wondering if there's a dependency that's not getting installed in my docker image?

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
