### ISSUE TITLE
Non-existent album causing mopidy crash

### ISSUE THREAD

**Issue by ScottG489** [mopidy/mopidy-gmusic#67]
So essentially an album in gmusic used to exist and now it doesn't. This seems to be causing mopidy-gmusic to crash. I have a song in one of my playlists (the ID is T2zl655curukztmg7zdkwtcas3a) that exists and it's album (Bhubivvfmgpqdhgecbeabivp4dy) which no longer exists https://play.google.com/music/listen#/album/Bhubivvfmgpqdhgecbeabivp4dy). I'm not sure what happened on Google's end that causes an album to long exist but it seems you possibly need to handle for the fact that this phenomenon can occur.
Below is a mopidy stacktrace and some corresponding lines from the gmusicapi.log file.

# Mopidy stacktrack with some context
```
2014-10-24 22:16:34,536 INFO [3503:MainThread] mopidy.commands: Starting Mopidy core
2014-10-24 22:19:37,904 ERROR [3503:GMusicBackend-3] mopidy_gmusic.session: Failed to get All Access album info: GetAlbum: 400 Client Error
: Bad Request
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/fetchalbum', 'headers': {'Authorization': '<omitted>'}, 'params': {'alt': 'jso
n', 'nid': u'Bhubivvfmgpqdhgecbeabivp4dy', 'include-tracks': False}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "badRequest",\n    "message": "Bad Request"\n   
}\n  ],\n  "code": 400,\n  "message": "Bad Request"\n }\n}\n')
2014-10-24 22:19:37,925 ERROR [3503:GMusicBackend-3] pykka: Unhandled exception in GMusicBackend (urn:uuid:a62c070e-93a9-446a-9fbf-04811bb2b
bf0):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/actor.py", line 31, in on_start
    self.playlists.refresh()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/playlists.py", line 32, in refresh
    track['trackId'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/library.py", line 73, in lookup
    return self._lookup_track(uri)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/library.py", line 86, in _lookup_track
    return [self._aa_to_mopidy_track(song)]
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/library.py", line 263, in _aa_to_mopidy_track
    date=album.date,
AttributeError: 'NoneType' object has no attribute 'date'
2014-10-24 22:19:37,941 ERROR [3503:MainThread] mopidy.commands: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 273, in run
    core = self.start_core(mixer, backends)
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 355, in start_core
    return Core.start(mixer=mixer, backends=backends).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 41, in __init__
    self.backends = Backends(backends)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 112, in __init__
    has_library = b.has_library().get()
  File "/usr/lib/python2.7/dist-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "<string>", line 1, in <module>
ActorDeadError: GMusicBackend (urn:uuid:a62c070e-93a9-446a-9fbf-04811bb2bbf0) stopped before handling the message
2014-10-24 22:19:37,958 INFO [3503:MainThread] mopidy.commands: Stopping Mopidy frontends
2014-10-24 22:19:37,965 INFO [3503:MainThread] mopidy.commands: Stopping Mopidy core
2014-10-24 22:19:37,969 INFO [3503:MainThread] mopidy.commands: Stopping Mopidy backends
2014-10-24 22:19:37,988 INFO [3503:MainThread] mopidy.commands: Stopping Mopidy audio
2014-10-24 22:19:38,003 INFO [3503:MainThread] mopidy.commands: Stopping Mopidy mixer
```

# Some relevant information from gmusicapi.log
```
2014-10-24 22:19:37,373 - gmusicapi.Mobileclient1 (shared:201) [DEBUG]: GetStoreTrack(args=[u'T2zl655curukztmg7zdkwtcas3a'], kwargs={})
2014-10-24 22:19:37,581 - gmusicapi.Mobileclient1 (shared:242) [DEBUG]: {u'albumArtRef': [{u'url': u'http://lh3.ggpht.com/CBJ95dFdFYXbubKVQdNvHx2wdyP0k2W6VCTXtQqFXI8JcUqLL3sYbRmQJFrI781A4Bp3tsFmXA'}], u'artistId': [u'As2qn3wdg2smzrnlylji43jfagy'], u'composer': u'Tove Lo', u'year': 2014, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Truth Serum', u'title': u'Stay High (Habits Remix)', u'albumArtist': u'Tove Lo', u'trackNumber': 6, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': False, u'storeId': u'T2zl655curukztmg7zdkwtcas3a', u'nid': u'T2zl655curukztmg7zdkwtcas3a', u'estimatedSize': u'10338247', u'albumId': u'Bhubivvfmgpqdhgecbeabivp4dy', u'genre': u'Pop', u'kind': u'sj#track', u'artist': u'Tove Lo', u'durationMillis': u'258000'}
2014-10-24 22:19:37,696 - gmusicapi.Mobileclient1 (shared:201) [DEBUG]: GetAlbum(args=[u'Bhubivvfmgpqdhgecbeabivp4dy', False], kwargs={})
```

**Comment by belak** [comment]
I ran into a few issues similar to this when doing my cache rewrite. The functions for converting between the gmusic api format and the internal mopidy format should be a bit cleaner (more shared code), and we handle a few more cases properly.

In particular, I think purchased tracks didn't work before, but they should now.

I'm going to close this for now because now as long as the initial request returns tracks which can be parsed as valid api tracks, mopidy-gmusic shouldn't crash.

**Comment by ScottG489** [comment]
Wow completely forgot about this haha. I don't use this software anymore but use a gmusic plugin for Kodi. However this was still a really great plugin and it's nice that you're still supporting and maintaining it. Thanks!
