### ISSUE TITLE
Uncaught exception kills gmusic actor when internet connection is lost

### ISSUE THREAD

**Issue by cpick** [mopidy/mopidy-gmusic#85]
When my internet connection dies, gmusicapi throws an exception.  The exception isn't caught and so mopidy-gmusic's pykka actor dies.  As a result mopidy can no longer stream from gmusic.

Here's an abbreviated traceback from mopidy's stderr, [full traceback here](https://gist.github.com/cpick/7ba00abfa64aa57ce08f): 

``` python
ERROR    Unhandled exception in Core (urn:uuid:f479ec63-0ba8-467b-aeb0-7b095ba0768f):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/listener.py", line 49, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 217, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 196, in _change_track
    self.stop()
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 396, in stop
    if not backend or backend.playback.stop().get():
  File "/usr/lib/python2.7/dist-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/playback.py", line 36, in stop
    self.backend.session.increment_song_playcount(track_id)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 152, in increment_song_playcount
    return self.api.increment_song_playcount(song_id, plays, playtime)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 160, in increment_song_playcount
    self._make_call(mobileclient.IncrementPlayCount, song_id, plays, playtime)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 142, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

*Edited to include full stack trace. -jodal*

**Comment by jodal** [comment]
Actually, Mopidy-GMusic's actor sends the exception to the Core actor, which is the one crashing. As of Mopidy 1.1.0, exceptions sent from backends to Core will only be logged with full traceback without crashing the Core actor, so the severity of this issue is reduced a bit.

I still think we should catch and log this exception in Mopidy-GMusic and return an empty result back to Core.
