### ISSUE TITLE
Unhandled ConnectionError from gmusicapi/requests

### ISSUE THREAD

**Issue by Stenvdb** [mopidy/mopidy-gmusic#98]
Hi, I'm not able to login with this extension.. I have fresh installs mopidy, gmusic, ... as of a couple days ago. Here is the full traceback of the error I get during start up:

    ERROR    Unhandled exception in GMusicBackend (urn:uuid:aa337f19-xxxx-xxxx-xxxx-02647030b8a5):
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/actor.py", line 31, in on_start
    self.playlists.refresh()
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/playlists.py", line 27, in refresh
    for playlist in self.backend.session.get_all_user_playlist_contents():
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 53, in get_all_user_playlist_contents
    return self.api.get_all_user_playlist_contents()
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 407, in get_all_user_playlist_contents
    updated_after=None)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1043, in _get_all_items
    return [s for chunk in generator for s in chunk]
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1056, in _get_all_items_incremental
    **kwargs)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 209, in perform
    response = session.send(req_kwargs, cls.required_auth)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/session.py", line 87, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/session.py", line 188, in _send_with_auth
    return rsession.request(**req_kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
    ConnectionError: ('Connection aborted.', ResponseNotReady())
    ERROR    Actor died: GMusicBackend (urn:uuid:aa337f19-xxxx-xxxx-xxxx-02647030b8a5) stopped before handling the message

**Comment by Stenvdb** [comment]
Update: I got a bit further with current gmusicapi master branch and gmusic dev branch. I also did that fix in sessions.py on line 21 (deviceid missing). Now it seems to connect at first but then I get:

    Exception in thread Thread-9:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/repeating_timer.py", line 12, in run
    self._method()
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/actor.py", line 78, in _refresh_library
    self.playlists.refresh()
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/playlists.py", line 64, in refresh
    for playlist in self.backend.session.get_all_user_playlist_contents():
      File "/usr/local/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 53, in get_all_user_playlist_contents
    return self.api.get_all_user_playlist_contents()
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 401, in get_all_user_playlist_contents
    user_playlists = [p for p in self.get_all_playlists()
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 304, in get_all_playlists
    playlists = self._get_all_items(mobileclient.ListPlaylists, incremental, include_deleted)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1044, in _get_all_items
    return [s for chunk in generator for s in chunk]
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 1057, in _get_all_items_incremental
    **kwargs)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
      File "/usr/local/lib/python2.7/site-packages/gmusicapi/session.py", line 195, in _send_with_auth
    return rsession.request(**req_kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
    ConnectionError: ('Connection aborted.', ResponseNotReady())

**Comment by riemers** [comment]
Don't know if this is related (its for spotify)

```
ERROR    Unhandled exception in SpotifyBackend (urn:uuid:5fc688e2-5525-4c1b-8eae-8e79baafbac8):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/backend.py", line 53, in on_start
    self._session = self._get_session(self._config)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/backend.py", line 69, in _get_session
    session = spotify.Session(self._get_spotify_config(config))
  File "/usr/local/lib/python2.7/site-packages/spotify/__init__.py", line 58, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 60, in __init__
    self.config._sp_session_config, sp_session_ptr))
  File "/usr/local/lib/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: Unable to open trace file
ERROR    Actor died: SpotifyBackend (urn:uuid:5fc688e2-5525-4c1b-8eae-8e79baafbac8) stopped before handling the message
```

**Comment by hunterboerner** [comment]
same here

**Comment by jodal** [comment]
Mopidy-GMusic should catch and log these exceptions instead of crashing. Other than that, it isn't much we can do with any error in the "network issue" category.

**Comment by Stenvdb** [comment]
So there is "no solution" here..?

**Comment by jodal** [comment]
You're saying this is a permanent issue? If so, do you have any firewalls or similar that could be causing this?

**Comment by Stenvdb** [comment]
Thanks for the quick response, yes I have this every time. No firewalls, have tried this on several locations as well so I don't think this is a network related issue. Is there an error log somewhere I can check perhaps?

**Comment by jodal** [comment]
Regular Mopidy debugging tips applies here as well: https://docs.mopidy.com/en/latest/troubleshooting/

Have you updated your Mopidy-GMusic develop install lately? I've fixed a number of issues over the last few days. Also make sure you have the latest gmusicapi.

**Comment by Stenvdb** [comment]
Yes I updated today. Running mopidy with debug logs on, the last 2 debug logs I get before the Exception are:

    DEBUG    2015-10-07 11:18:03,287 [68576:HttpFrontend-14] mopidy.zeroconf
      Zeroconf service _http._tcp at [mbpvansdenbergh.telenet.be.local]:6680: dbus not installed; publish     failed.
    DEBUG    2015-10-07 11:18:03,288 [68576:HttpFrontend-14] mopidy.zeroconf
      Zeroconf service _mopidy-http._tcp at [mbpvansdenbergh.telenet.be.local]:6680: dbus not installed;     publish failed.

I guess it is a network issue after all, do you have any idea how to fix this?

**Comment by jodal** [comment]
The Zeroconf log messages are unrelated, and not serious, thus the "DEBUG" error level.

Can you reproduce the issue with the following Python script? If so, the issue is independent of Mopidy and you should report the issue in the gmusicapi issue tracker.

``` python
import gmusicapi
api = gmusicapi.Mobileclient()
api.login(
    'your-google-username', 'your-google-password',
    gmusicapi.Mobileclient.FROM_MAC_ADDRESS)
api.get_all_user_playlist_contents()
```

**Comment by jodal** [comment]
With #85 fixed, network exceptions are just logged and the default return value used. In other words, this issue is currently just about helping to find the reason for @Stenvdb's persistent network issues.

**Comment by jodal** [comment]
No response in >7 weeks, closing.
